services:
  customers-service:
    build: ./CustomersService
    image: 'customers-service:0.0.1-SNAPSHOT'
    ports:
    - '8080:8080'
  content-service:
    build: ./ContentService
    image: 'content-service:0.0.1-SNAPSHOT'
    ports:
    - '8081:8080'
  s3-service:
    build: ./S3Service
    image: 's3-service:0.0.1-SNAPSHOT'
    ports:
    - '8082:8080' 